version: 2
jobs:
  build_8:
    docker:
      - image: circleci/node:8.17.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test

  build_10:
    docker:
      - image: circleci/node:10.18.1
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test

  build_12:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test

  publish:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: yarn install --frozen-lockfile || yarn install --frozen-lockfile || yarn install --frozen-lockfile
      - run: yarn run build
      - run: ./node_modules/.bin/journey-deploy execute

workflows:
  version: 2
  build:
    jobs:
      - build_8
      - build_10
      - build_12
